# 名称
name: ZhaiFanhuaBlog.Framework

# 触发条件：在 push 和 pull 到 main 分支后
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 任务
jobs:
  build:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest

    steps:
    # 拉取代码
    - uses: actions/checkout@v3
    # 环境
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet ZhaiFanhuaBlog.Framework/ZhaiFanhuaBlog.sln
    - name: Build
      run: dotnet build --no-restore ZhaiFanhuaBlog.Framework/ZhaiFanhuaBlog.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ZhaiFanhuaBlog.Framework/ZhaiFanhuaBlog.sln
