# 名称
name: ZhaiFanhuaBlog.Framework

# 触发条件：在 push 和 pull 到 main 分支后
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# 任务
jobs:
  build:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ZhaiFanhuaBlog.Framework

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet ZhaiFanhuaBlog.sln
    - name: Build
      run: dotnet build --no-restore ZhaiFanhuaBlog.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ZhaiFanhuaBlog.sln
