# 名称
name: XiHan.Framework Publish Test

# 触发条件：在 push 和 pull 到 main 分支后
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# 任务
jobs:
  build:
    # 服务器环境：最新版 Ubuntu
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./xihan-framework/src/

    steps:
      # 拉取代码
      - uses: actions/checkout@v3
      # 环境
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore XiHan.sln
      - name: Build
        run: dotnet build --no-restore XiHan.sln
      - name: Test
        run: dotnet test --no-build --verbosity normal XiHan.sln
